name: e_imzo
description: "E-imzo bilan ishlash uchun package"
version: 0.0.1
repository: https://github.com/abbos2101/e_imzo
homepage: https://www.linkedin.com/in/abbos2101/
topics: [ e-imzo, imzo, soliq, one-id ]
funding: [ https://github.com/sponsors/abbos2101 ]

environment:
  sdk: '>=2.12.0 <4.0.0'

dev_dependencies:
  flutter_lints: ^6.0.0